os: linux
dist: bionic
language: shell

branches:
  only: master

notifications:
  email: false

addons:
  apt:
    packages:
      - aggregate
      - git
      - gcc
      - g++
      - make

env:
  global:
    - TZ: "Asia/Hong_Kong"
    - secure: "U4S7PKECmegpzEoHwblNnRQ4Wgzn7fE4nYv+GGbumxd98z71RcoKBJP0hQg9zxHRFQdPmUid9sRPW7P6E2HPwPVCeWjTkntWMFcF2PZr9fW/beO31LUe5R+0KS7BaKl2IVrHJeSURpOtv3RMJRzo838WfzuiSlD5EumJ23+2e0GDjcoREWw+p3f7cDi8De4PUoVN1atig2ZN/Y6Gr8JNSbAAjUj2ECd/BQRRrIxe/ri/7dHs5Uot9gPbG2VNCAi+srla9fSLUrtXYRY5k3uI9FyCb2yu8MIW0IeiJrx06onYd6F3pJ49QxJfsRJtFEa3FMmMBE2U4XlnTq/pMdcVgCqle4KSK2G0WQ4oU7l3Fbk9qqTVHOZIJQBPkSQUbBeQ1MBSiWR0O6t0AVbNDsWaO/PFb2Y8qQWiJC9XVCZ+t6xE/InUyX/kom1NuEd86GhESpr6lxGImJ4WIlUYZ37eWI9vZBqwKp1yVzMEmIUkld4/no6/IWtWcdxYVsI62aZNUtHuHFelGaR3tC2M3w+SoEfcciXM++4gcUHyBqZTRmkAsCbdxB4ag7IZG83Ij0GcfSyDc3UVU//A6Q4e7E1py1GsTssVTrbcfV3Xwzd9rroyXlMo1c6ACMV1nT5MInBrxxykySJ/qkPKPfTtcFUik5HLcp/xhhJlfaQOha7ZFgA="

script:
  - ./generate.sh

deploy:
  edge: true
  strategy: git
  provider: pages
  local_dir: release
  target_branch: gh-pages
  keep_history: true
  name: Deployment Bot
  email: deploy@travis-ci.org
  commit_message: $(date '+%Y-%m-%d %H:%M:%S')
  token: ${token}
  on:
    branch: master
