dist: trusty
language: bash

branches:
  only: master

notifications:
  email: false

addons:
  apt:
    packages:
      - aggregate

env:
  global:
    - secure: "U4S7PKECmegpzEoHwblNnRQ4Wgzn7fE4nYv+GGbumxd98z71RcoKBJP0hQg9zxHRFQdPmUid9sRPW7P6E2HPwPVCeWjTkntWMFcF2PZr9fW/beO31LUe5R+0KS7BaKl2IVrHJeSURpOtv3RMJRzo838WfzuiSlD5EumJ23+2e0GDjcoREWw+p3f7cDi8De4PUoVN1atig2ZN/Y6Gr8JNSbAAjUj2ECd/BQRRrIxe/ri/7dHs5Uot9gPbG2VNCAi+srla9fSLUrtXYRY5k3uI9FyCb2yu8MIW0IeiJrx06onYd6F3pJ49QxJfsRJtFEa3FMmMBE2U4XlnTq/pMdcVgCqle4KSK2G0WQ4oU7l3Fbk9qqTVHOZIJQBPkSQUbBeQ1MBSiWR0O6t0AVbNDsWaO/PFb2Y8qQWiJC9XVCZ+t6xE/InUyX/kom1NuEd86GhESpr6lxGImJ4WIlUYZ37eWI9vZBqwKp1yVzMEmIUkld4/no6/IWtWcdxYVsI62aZNUtHuHFelGaR3tC2M3w+SoEfcciXM++4gcUHyBqZTRmkAsCbdxB4ag7IZG83Ij0GcfSyDc3UVU//A6Q4e7E1py1GsTssVTrbcfV3Xwzd9rroyXlMo1c6ACMV1nT5MInBrxxykySJ/qkPKPfTtcFUik5HLcp/xhhJlfaQOha7ZFgA="
    - TZ: "Asia/Shanghai"

script:
  - bash bootstrap.sh

deploy:
  provider: pages
  local-dir: dist
  target-branch: gh-pages
  keep-history: true
  skip-cleanup: true
  github-token: ${token}
  name: Travis CI
  email: travis.ci.build@gmail.com
  on:
    branch: master
